### ISSUE TITLE
Prompt

### ISSUE THREAD

**Issue by JeremyChooCK** [JeremyChooCK/42-Minishell#1]
Display a prompt when waiting for a new command.

    Execute a simple command with an absolute path like /bin/ls, or any other command without any options.
    How many global variables are used? Why? Ask the evaluated student to give you a concrete example of why it feels mandatory or logical.
    Check the global variable. This global variable cannot provide any other information or data access than the number of a received signal.
    Test an empty command.
    Test only spaces or tabs.
Execute a simple command with an absolute path like /bin/ls, or any other command with arguments but without any quotes or double quotes.
Repeat multiple times with different commands and arguments.

**Comment by jgyy** [comment]
try to write the function in the way where it continuously listen to the user input, printf to prompt display logic, readline to read input from user.
