### ISSUE TITLE
Implement pipes (| character)

### ISSUE THREAD

**Issue by JeremyChooCK** [JeremyChooCK/42-Minishell#4]
The output of each command in the pipeline is
connected to the input of the next command via a pipe.

**Comment by JeremyChooCK** [comment]
pipes implemented, but invalid command does not output correctly yet

**Comment by jgyy** [comment]
`curl https://raw.githubusercontent.com/LucasKuhn/minishell_tester/main/test_files/infile_big | grep oi`

try running this command in minishell, this pipe does not work.

**Comment by JeremyChooCK** [comment]
> `curl https://raw.githubusercontent.com/LucasKuhn/minishell_tester/main/test_files/infile_big | grep oi`
> 
> try running this command in minishell, this pipe does not work. this is a valid command for normal shell command.

Fixed
