### ISSUE TITLE
implement echo

### ISSUE THREAD

**Issue by JeremyChooCK** [JeremyChooCK/42-Minishell#7]
Execute the echo command with or without arguments, or the -n option.
Repeat multiple times with different arguments.
If something crashes, select the "crash" flag.
If something doesn't work, select the "incomplete work" flag

**Comment by JeremyChooCK** [comment]
echo does not work with flags yet

**Comment by jgyy** [comment]
Test   1: ✅ echo hello world 
Test   2: ❌ echo "hello world" 
mini output = ("hello world")
bash output = (hello world)
Test   3: ❌ echo 'hello world' 
mini output = ('hello world')
bash output = (hello world)
Test   4: ❌ echo hello'world' 
mini output = (hello'world')
bash output = (helloworld)
Test   5: ❌ echo hello""world 
mini output = (hello""world)
bash output = (helloworld)
Test   6: ❌ echo '' 
mini output = ('')
bash output = ()
Test   7: ❌ echo "$PWD" 
mini output = ("$PWD")
bash output = (/Users/jgyy/Documents/repo/42-Minishell/minishell_tester)
Test   8: ❌ echo '$PWD' 
mini output = ('$PWD')
bash output = ($PWD)
Test   9: ❌ echo "aspas ->'" 
mini output = ("aspas ->'")
bash output = (aspas ->')
Test  10: ❌ echo "aspas -> ' " 
mini output = ("aspas -> ' ")
bash output = (aspas -> ' )
Test  11: ❌ echo 'aspas ->"' 
mini output = ('aspas ->"')
bash output = (aspas ->")
Test  12: ❌ echo 'aspas -> " ' 
mini output = ('aspas -> " ')
bash output = (aspas -> " )
Test  13: ❌ echo "> >> < * ? [ ] | ; [ ] || && ( ) & # $  <<" 
mini output = ("> >> < README.md bash.supp bash_outfiles bonus bonus_bonus builtins extras local.supp loop.out manual_tests mini_outfiles os_specific outfiles outlog.txt pipes redirects syntax test_files tester wildcards ? [ ] | ; [ ] || && ( ) & # $ <<")
bash output = (> >> < README.md bash.supp bash_outfiles bonus bonus_bonus builtins extras local.supp loop.out manual_tests mini_outfiles os_specific outfiles outlog.txt pipes redirects syntax test_files tester wildcards ? [ ] | ; [ ] || && ( ) & # $ <<)
Test  14: ❌ echo '> >> < * ? [ ] | ; [ ] || && ( ) & # $  <<' 
mini output = ('> >> < README.md bash.supp bash_outfiles bonus bonus_bonus builtins extras local.supp loop.out manual_tests mini_outfiles os_specific outfiles outlog.txt pipes redirects syntax test_files tester wildcards ? [ ] | ; [ ] || && ( ) & # $ <<')
bash output = (> >> < README.md bash.supp bash_outfiles bonus bonus_bonus builtins extras local.supp loop.out manual_tests mini_outfiles os_specific outfiles outlog.txt pipes redirects syntax test_files tester wildcards ? [ ] | ; [ ] || && ( ) & # $ <<)
Test  15: ❌ echo "exit_code ->$? user ->$USER home -> $HOME" 
mini output = ("exit_code ->$? user ->$USER home -> $HOME")
bash output = (exit_code ->0 user ->jgyy home -> /Users/jgyy)
Test  16: ❌ echo 'exit_code ->$? user ->$USER home -> $HOME' 
mini output = ('exit_code ->$? user ->$USER home -> $HOME')
bash output = (exit_code ->$? user ->$USER home -> $HOME)
Test  17: ❌ echo "$" 
mini output = ("$")
bash output = ($)
Test  18: ❌ echo '$' 
mini output = ('$')
bash output = ($)
Test  19: ✅ echo $ 
Test  20: ❌ echo $? 
mini output = ($?)
bash output = (0)
Test  21: ❌ echo $?HELLO 
mini output = ($?HELLO)
bash output = (0HELLO)

**Comment by jgyy** [comment]
I did a partial implementation for exit code, so you can continue to test on echo. thanks a lot

**Comment by jgyy** [comment]
minishell tester actually does work, but the reason why it fails is because i use printf for prompting, should use readline for prompt instead, i fixed that

**Comment by jgyy** [comment]
i went to check again, need to manually write the buildin for echo, not to use /usr/bin/echo.

**Comment by jgyy** [comment]
went to do another test for the day, even if custom implementation of echo is being written, it still automatically picks echo from existing PATH instead of a custom 1, need to think of a way to fix it.
