### ISSUE TITLE
implement exit

### ISSUE THREAD

**Issue by JeremyChooCK** [JeremyChooCK/42-Minishell#8]
Execute exit command with or without arguments.
    Repeat multiple times with different arguments.
    Don't forget to relaunch the minishell
    If something crashes, select the "crash" flag.
    If something doesn't work, select the "incomplete work" flag.

**Comment by jgyy** [comment]
to implement exit or else test cases will just fail....

**Comment by jgyy** [comment]
already implemented yesterday
