### ISSUE TITLE
Single and Double quotes

### ISSUE THREAD

**Issue by JeremyChooCK** [JeremyChooCK/42-Minishell#9]
Double Quotes

    Execute a simple command with arguments and, this time, use also double quotes (you should try to include whitespaces too).
    Try a command like : echo "cat lol.c | cat > lol.c"
    Try anything except $.
    If something crashes, select the "crash" flag.
    If something doesn't work, select the "incomplete work" flag.

Single Quotes

    Execute commands with single quotes as arguments.
    Try empty arguments.
    Try environment variables, whitespaces, pipes, redirection in the single quotes.
    echo '$USER' must print "$USER".
    Nothing should be interpreted.

**Comment by jgyy** [comment]
every single command need to handle single quote, double quote and environment variable, that function need to be written first prior to handling commands.

**Comment by jgyy** [comment]
already settled
